apiVersion: apps/v1
kind: Deployment
metadata: 
     name: mavenproject
     labels: 
        app: webapp 
spec:
     replicas: 1
     selector:
        matchLabels:
           app: webapp
     template:
        metadata:
           labels:
              app: webapp
        spec:
           containers:
            - name: tomcat
              image:                  